### ISSUE TITLE
utf8 and general checklist

### ISSUE THREAD

**Issue by matu3ba** [matu3ba/chepa#4]
1. [ ] formulate assumptions for linebreak characters on OSes
2. [ ] create CI
3. [ ] automate benchmarks in build.zig

Incomplete list to check for utf8
- [ ] ~~slow path as another cli flag for validating correct utf8, TODO: check zigstr examples etc~~
- [x] use std.unicode to interpret the bits as utf8 (for perf reasons)
- [x] use jump tag with state machine for parsing all paths
- [ ] control characters, TODO: check utf8 cntrl chars
- [x] forbid whitespaces except the simple one
- [x] forbid prefixed dashes
- [x] forbid prefixed and postfixed whitespace
- [ ] apply the utf8 checks to shell+file output with correct return codes/error handling.

Other perf improvements:
- [ ] use buffered output (rather simple)
- [ ] use buffer-backed allocator instead of allocating space (move stuff into library file)
- [ ] comptime-construct string message offsets for printing (stage2)
- [ ] optimize len fields (tedious)

**Comment by matu3ba** [comment]
zigstr provides printing/rendering support and meta information.
std.unicode only provides the unicode codepoints, which need to be combined to get aforementioned information.
